1. Consider an electron in a 1D box of length 1 nm with energy eigenstates given by $\psi_n(x) = \sqrt{2} {\rm sin}(n \pi x)$ when $x$ has units of nanometers.  Now consider that an atomically-precise hammer has been used to deform the bottom of the box, such that the electron feels an effective potential given by $V(x) = 2(x-0.5)^2 - 0.5$.

**Compute $\langle E \rangle$ for $\psi_1$**.

First thing I am going to do is convert my length units into meters so that I am now in SI units.  In SI units, the energy eigenfunctions will be

\begin{equation}
\psi_n(x) = \sqrt{ \frac{2}{1 \cdot 10^{-9}} } {\rm sin}(\frac{n \pi x}{1 \cdot 10^{-9}})
\end{equation}

and the potential is

\begin{equation}
V(x) = 2(x-0.5\cdot 10^{-9} )^2 - 0.5\cdot 10^{-9}.
\end{equation}

The energy expectation value is then the sum of integrals over the
ordinary PIB Hamiltonian (kinetic energy only) and the potential:
\begin{equation}
\langle E \rangle = \langle \psi_1(x) | -\frac{\hbar^2}{2m} \frac{d^2}{dx^2}| \psi_1(x) \rangle + \langle \psi_1(x) | 2(x-0.5\cdot 10^{-9} )^2 - 0.5\cdot 10^{-9}| \psi_1(x) \rangle. 
\end{equation}

The first term, which I will call $\langle T \rangle$, I know immediately because $\psi_1(x)$ is an eigenfunction of the kinetic energy operator, $\hat{T}$, because it is 
equivalent to the ordinary PIB Hamiltonian:
\begin{equation}
\langle \psi_1(x) | -\frac{\hbar^2}{2m} \frac{d^2}{dx^2}| \psi_1(x) \rangle = \langle \psi_1(x) | E_1 | \psi_1(x) \rangle = E_1 \langle \psi_1(x) | \psi_1(x) \rangle = E_1,
\end{equation}
where $E_1 = \frac{\pi^2 \hbar^2}{2 m L^2}$.  Let's compute this value numerically in SI units (J):


In [3]:
import numpy as np
### hbar in SI units, J*s
hbar = 1.054571e-34 
### electron mass in SI units, kg
m = 9.109383e-31
### Length of the box in SI units, m
L = 1e-9
### pi
pi = np.pi

### E1 in SI units
E1 = pi**2 * hbar**2/(2 * m * L**2)
print(E1, "J")

6.024658523923367e-20 J


The second term, which I will call $\langle V \rangle$, I don't automatically know, but I can use Wolfram Alpha to compute... here is a how I input the integral into Wolfram Alpha: 

`integrate (2/1e-9)*sin^2(pi*x/1e-9)*(2 *(x-0.5e-9)^2 - 0.5e-9) from x = 0 to 1e-9 `

and the result is $\langle V \rangle = -5 \cdot 10^{-10} J$.

The total energy expectation value is just the sum of $\langle T \rangle$ and $\langle V \rangle$:
\begin{equation}
\langle E \rangle = 6.024\cdot 10^{-20} J - 5.000 \cdot 10^{-10} J = -4.999 \cdot 10^{-10} J.
\end{equation}

**Use the time-dependent Schrodinger equation to see if $\psi_n(x)$ are stationary states in the deformed box**

There's a few different ways to approach this problem, but the most economical way I can think of is to recognize why it is that energy eigenfunctions are stationary states in the first place.  

Consider the time-dependent Schrodinger equation for a particle that has a well-defined energy, which is to say for a particle in an energy eigenstate which we will denote $\psi_n(x,t)$:
\begin{equation}
i\hbar \frac{d}{dt} \psi_n(x,t) = \hat{H} \psi_n(x,t) = E_n \psi_n(x,t),
\end{equation}
where the final expression on the right hand side is **only true** because $\psi_n(x)$ is
an energy eigenfunction (for a more generic state $\Psi$ that does not have well-defined energy,
only $i\hbar \frac{d}{dt} \Psi = \hat{H} \Psi$ is true!).

In the event that we are dealing with an energy eigenfunction, the time-dependent Schrodinger equation can be solved rather easily to give a general expression for how the state evolves in time:
\begin{equation}
i\hbar \frac{d}{dt} \psi_n(x,t) = E_n \psi_n(x,t) \rightarrow \psi_n(x,t) = \psi_n(x) \cdot {\rm exp}(-i E_n t/\hbar).
\end{equation}
We say this is a stationary state because the probability density function associated with this state does not change with time!
\begin{equation}
P_n(x,t) = \psi_n^*(x,t) \psi_n(x,t) = \psi_n^*(x)\cdot {\rm exp}(i E_n t/\hbar) \psi_n(x) \cdot {\rm exp}(-i E_n t/\hbar) = \psi_n^*(x)\psi_n(x).
\end{equation}

This feature is **ONLY** true for states which are eigenfunctions of the Hamiltonian, so the most economical way to determine if $\psi_n(x)$ are stationary in the deformed box is to see if they are eigenfunctions of the deformed box Hamiltonian:
\begin{equation}
\hat{H} \psi_n(x) = \hat{T} \psi_n(x) + \hat{V} \psi_n(x) = E_n \psi_n(x) + 2(x-0.5)^2 \psi_n(x) - 0.5 \psi_n(x).
\end{equation}
In the above, we should immediately recognize that the action of the Hamiltonian on $\psi_n(x)$ yields a term $2(x-0.5)^2\psi_n(x)$, which is not simply a constant times the original function, hence $\psi_n(x)$ are not eigenfunctions of the deformed box Hamiltonian.
Since they are not eigenfunctions of this Hamiltonian, **they are not stationary!**


2.  Use the Linear Variational Principle in the basis of the first 3 energy eigenstates to estimate the ground state energy of the particle in the deformed box.

This is very similar to our Computational Problem set, only the potential is different.
The Hamiltonian we are dealing with in this case is (in SI units)
\begin{equation}
\hat{H} = \frac{-\hbar^2}{2m} \frac{d^2}{dx^2} + 2(x-0.5 \cdot 10^{-9})^2 - 0.5\cdot 10^{-9}.
\end{equation}

Just as we did before, we will build a Hamiltonian matrix in the basis of the first
3 energy eigenfunctions of the ordinary particle in a box and diagonalize that Hamiltonian to determine the lowest energy eigenvalues for the deformed system.  These Hamiltonian matrix elements can be computed as follows:
\begin{equation}
H_{ij} = \langle \psi_i(x) | \hat{H} | \psi_j(x) \rangle.
\end{equation}

As before, the diagonal elements will be
\begin{equation}
H_{ii} = E_i + \langle \psi_i(x) | \hat{V} | \psi_i(x) \rangle
\end{equation}
where $E_i$ is the ordinary PIB energy eigenvalue for state $i$ and
the off-diagonal elements will be
\begin{equation}
H_{ij} =  \langle \psi_i(x) | \hat{V} | \psi_j(x) \rangle.
\end{equation}

We could do the potential integrals in Wolfram Alpha like before, but let's write a little python code to do it here:

In [38]:
### repeating constants here so this cell can stand alone!
import numpy as np
### hbar in SI units, J*s
hbar = 1.054571e-34 
### electron mass in SI units, kg
m = 9.109383e-31
### Length of the box in SI units, m
L = 1e-9
### pi
pi = np.pi

### let's go ahead and define a coordinate system for our system
x = np.linspace(0,L,200)
### and let's also define the potential function on this coordinate system
Vx = 2*(x-0.5e-9)**2 - 0.5e-9

def Hij(I, J, xarray, pot_array):
    ### for diagonal elements, get the E_i contribution
    if (I==J):
        Ei = pi**2 * hbar**2 * I**2/(2*m*L**2)
    else:
        Ei = 0.
    
    ### Now do potential energy integral
    ### get dx on this grid called xarray
    dx = xarray[1] - xarray[0]
    ### define psi_i
    psi_i = np.sqrt(2/L) * np.sin( I * pi * xarray/L)
    ### define psi_j
    psi_j = np.sqrt(2/L) * np.sin( J * pi * xarray/L)
    ### define psi_i * V * psi_j
    integrand = psi_i * pot_array * psi_j
    ### define variable to accumulate sum of integral
    pot_int = 0.
    ### compute rectangle rule approximation to integral
    for i in range(0,len(xarray)):
        pot_int = pot_int + integrand[i]*dx
    
    return (Ei + pot_int)

H_mat = np.zeros((3,3))
for i in range(1,4):
    for j in range(1,4):
        H_mat[i-1][j-1] = Hij(i, j, x, Vx)

print(H_mat)
    
E_opt, c_opt = np.linalg.eig(H_mat)

### print lowest eigenvalues corresponding to the 
### variational estimate of the ground state energy
print("Estimate of ground state energy is ",np.min(E_opt), "Joules")


[[-5.00000000e-10 -3.60903864e-27  7.59909117e-20]
 [ 2.22403555e-26 -5.00000000e-10 -2.42290738e-26]
 [ 7.59908895e-20 -2.66524545e-26 -4.99999999e-10]]
Estimate of ground state energy is  -4.999999998843308e-10 Joules


3.  Compare the energies of the Hartree wavefunction $\Psi_H$ to the Hatree-Fock wavefunction $\Psi_{HF}$.

The Hartree wavefunction for the minimal basis model of $H_2$ can be written as
\begin{equation}
\Psi_H(x_1, x_2) = \phi_1(x_1) \phi_2(x_2)
\end{equation}
while the Hartree-Fock wavefunction for the minimal basis model of $H_2$ can be written as
\begin{equation}
\Psi_{HF}(x_1, x_2) = \frac{1}{2}\left(\phi_1(x_1) \phi_2(x_2) - \phi_1(x_2) \phi_2(x_1)   \right).
\end{equation}
The total energy is expectation value of the wavefunction with the Hamiltonian operator, which for $H_2$, can be written symbolically as
\begin{equation}
\hat{H} = \hat{h}_1 + \hat{h}_2 + \hat{V}_{12}
\end{equation}
where $\hat{h}_i$ is the one-electron operator for electron $i$ and 
$\hat{V}_{ij}$ is the 2-electron operator for the pair of electrons $i$ and $j$.
We can write the energy expectation value for the Hartree wavefunction then is
\begin{equation}
\langle \phi_1(x_1) \phi_2(x_2) | \hat{H} | \phi_1(x_1) \phi_2(x_2) \rangle = 
\langle \phi_1(x_1) | \hat{h}_1 | \phi_1(x_1) \rangle + \langle \phi_1(x_2) | \hat{h}_2 | \phi_1(x_2) \rangle + \langle \phi_1(x_1) \phi_1(x_2) | \hat{V}_{12} | \phi_1(x_1) \phi_1(x_2) \rangle
\end{equation}
where we have used the fact that
\begin{equation}
\langle \phi_1(x_1) \phi_1(x_2) | \hat{h}_1 | \phi_1(x_1) \phi_1(x_2) \rangle = 
\langle \phi_1(x_1) | \hat{h}_1 | \phi_1(x_1) \rangle \langle \phi_2(x_2) | \phi_2(x_2) \rangle
= \langle \phi_1(x_1) | \hat{h}_1 | \phi_1(x_1) \rangle
\end{equation}

The energy expectation value for the Hartree-Fock wavefunction is
\begin{equation}
\frac{1}{2} \langle \phi_1(x_1) \phi_2(x_2) | \hat{H} | \phi_1(x_1) \phi_2(x_2) \rangle - 
\frac{1}{2} \langle \phi_1(x_2) \phi_2(x_1) | \hat{H} | \phi_1(x_1) \phi_2(x_2) \rangle - 
\frac{1}{2} \langle \phi_1(x_1) \phi_2(x_2) | \hat{H} | \phi_1(x_2) \phi_2(x_1) \rangle + 
\frac{1}{2} \langle \phi_1(x_2) \phi_2(x_1) | \hat{H} | \phi_1(x_2) \phi_2(x_1) \rangle
\end{equation}
Only the first and last term contribute to the one-electron terms; the first term has the following contributions
from electron 1 and electron 2:
\begin{equation}
\frac{1}{2} \langle \phi_1(x_1)  | \hat{h}_1 | \phi_1(x_1)  \rangle + \frac{1}{2} \langle \phi_2(x_2)  | \hat{h}_2 | \phi_2(x_2)  \rangle,
\end{equation}
and the last term has the following contributions from electron 1 and electron 2:
\begin{equation}
\frac{1}{2} \langle \phi_1(x_2)  | \hat{h}_2 | \phi_1(x_2)  \rangle + \frac{1}{2} \langle \phi_2(x_1)  | \hat{h}_1 | \phi_2(x_1)  \rangle.
\end{equation}
All terms have 2-electron contributions:
\begin{equation}
\frac{1}{2} \langle \phi_1(x_1) \phi_2(x_2) | \hat{V}_{12} | \phi_1(x_1) \phi_2(x_2) \rangle - 
\frac{1}{2} \langle \phi_1(x_2) \phi_2(x_1) | \hat{V}_{12} | \phi_1(x_1) \phi_2(x_2) \rangle - 
\frac{1}{2} \langle \phi_1(x_1) \phi_2(x_2) | \hat{V}_{12} | \phi_1(x_2) \phi_2(x_1) \rangle + 
\frac{1}{2} \langle \phi_1(x_2) \phi_2(x_1) | \hat{V}_{12} | \phi_1(x_2) \phi_2(x_1) \rangle.
\end{equation}
In the end, after combining like terms, we have the energy expectation value for the Hartree-Fock wavefunction is
\begin{equation}
langle \phi_1(x_1) | \hat{h}_1 | \phi_1(x_1) \rangle + \langle \phi_1(x_2) | \hat{h}_2 | \phi_1(x_2) \rangle + \langle \phi_1(x_1) \phi_1(x_2) | \hat{V}_{12} | \phi_1(x_1) \phi_1(x_2) \rangle - \langle \phi_1(x_1) \phi_1(x_2) | \hat{V}_{12} | \phi_2(x_1) \phi_1(x_2) \rangle.
\end{equation}

Typically, since the 2-electron integrals will be positive, and the Hartree-Fock energy contains an additional **negative** contribution from one such integral, its energy will tend to be lower than the energy for the Hartree wavefunction.

### Use the following trial wavefunction for the particle-in-a-box ground state:
\begin{equation}
\phi(x) = c_1 x(L-x) + c_2(L-x)^2 + c_3 x^4(L - x) + c_4 x^2(L-x)^2.
\end{equation}
and compare the trial energy to the ground state of the particle in a box, comment on if this is consistent with the variational principle.

{\bf NOTE:} We will make two assumptions to make this problem more concrete and more simple:

(1) we will assume $L = 1$ in atomic units

(2) we will assume all coefficients ($c_1, c_2,$) etc. are equal to 1.

What I want to do is compute the following expectation value:
\begin{equation}
\langle E \rangle = \frac{\langle \phi(x) | \hat{H} | \phi(x) \rangle}{\langle \phi(x) | \phi(x) \rangle}.
\end{equation}

I will compute the numerator in Wolfram Alpha with the following input:
`integrate -1/2 * (-20 x^3 + 24 x^2 - 6 x - 4)*( x(1-x)+ x(1-x)^2+ x^4 (1-x)+  x^2 (1-x)^2) from x = 0 to 1`

Note that I got the action of the Hamiltonian on the trial wavefunction by evaluating
`d^2/dx^2 of x(1-x)+ x(1-x)^2+ x^4 (1-x)+  x^2 (1-x)^2` and then multiplying by $-1/2$.

The value of the numerator turns out to be about 0.60317 atomic units

I will compute the denominator in Wolfram Alpha with the following input:
`integrate ( x(1-x)+ x(1-x)^2+ x^4 (1-x)+  x^2 (1-x)^2)^2 from x = 0 to 1`

The value of the denominator turns out to be about 0.11948.

The energy expectation value is therefore
\begin{equation}
\langle E \rangle = \frac{0.60317 a.u.}{0.11948} = 5.0482 a.u.
\end{equation}

I can evaluate the ground state energy immediately from 
\begin{equation}
E_1 = \frac{1^2 \pi^2}{2} = 4.9348 a.u.
\end{equation}

This result is consistent with the variational principle because the energy of the trial wavefunction is greater than the true ground state energy!

### How does the computational cost of the energy expression for Hartree-Fock theory increase with the number of basis functions?

The Hartree-Fock energy can be expressed as
\begin{equation}
E_{HF} = \sum_{i=1}^N \langle i | h | i \rangle + \sum_{i=1}^N \sum_{j>i}^N \langle ij | V | ij \rangle - \langle ij | V | ji \rangle,
\end{equation}
where $N$ indicates the number of basis functions.
The computational cost will scale quadratically because of the nested for 
loops that each must count (approximately) the total number of basis functions!

